PLUGIN_NAME=		kea-ddns
PLUGIN_VERSION=		1.3.1
PLUGIN_COMMENT=		Kea DHCP Dynamic DNS (DDNS) support
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://brendanbank.github.io/opnsense-kea-ddns/

.include "../../Mk/plugins.mk"
